/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffUsersRouteImport } from './routes/staff.users'
import { Route as StaffPandaRouteImport } from './routes/staff.panda'
import { Route as StaffOrdersRouteImport } from './routes/staff.orders'
import { Route as StaffMenuRouteImport } from './routes/staff.menu'
import { Route as StaffDiscountsRouteImport } from './routes/staff.discounts'
import { Route as StaffAuditRouteImport } from './routes/staff.audit'
import { Route as OrderIdRouteImport } from './routes/order.$id'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffUsersRoute = StaffUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPandaRoute = StaffPandaRouteImport.update({
  id: '/panda',
  path: '/panda',
  getParentRoute: () => StaffRoute,
} as any)
const StaffOrdersRoute = StaffOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StaffRoute,
} as any)
const StaffMenuRoute = StaffMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => StaffRoute,
} as any)
const StaffDiscountsRoute = StaffDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAuditRoute = StaffAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => StaffRoute,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/history': typeof HistoryRoute
  '/menu': typeof MenuRoute
  '/staff': typeof StaffRouteWithChildren
  '/order/$id': typeof OrderIdRoute
  '/staff/audit': typeof StaffAuditRoute
  '/staff/discounts': typeof StaffDiscountsRoute
  '/staff/menu': typeof StaffMenuRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/panda': typeof StaffPandaRoute
  '/staff/users': typeof StaffUsersRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/history': typeof HistoryRoute
  '/menu': typeof MenuRoute
  '/order/$id': typeof OrderIdRoute
  '/staff/audit': typeof StaffAuditRoute
  '/staff/discounts': typeof StaffDiscountsRoute
  '/staff/menu': typeof StaffMenuRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/panda': typeof StaffPandaRoute
  '/staff/users': typeof StaffUsersRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/history': typeof HistoryRoute
  '/menu': typeof MenuRoute
  '/staff': typeof StaffRouteWithChildren
  '/order/$id': typeof OrderIdRoute
  '/staff/audit': typeof StaffAuditRoute
  '/staff/discounts': typeof StaffDiscountsRoute
  '/staff/menu': typeof StaffMenuRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/panda': typeof StaffPandaRoute
  '/staff/users': typeof StaffUsersRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/history'
    | '/menu'
    | '/staff'
    | '/order/$id'
    | '/staff/audit'
    | '/staff/discounts'
    | '/staff/menu'
    | '/staff/orders'
    | '/staff/panda'
    | '/staff/users'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/history'
    | '/menu'
    | '/order/$id'
    | '/staff/audit'
    | '/staff/discounts'
    | '/staff/menu'
    | '/staff/orders'
    | '/staff/panda'
    | '/staff/users'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/history'
    | '/menu'
    | '/staff'
    | '/order/$id'
    | '/staff/audit'
    | '/staff/discounts'
    | '/staff/menu'
    | '/staff/orders'
    | '/staff/panda'
    | '/staff/users'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  HistoryRoute: typeof HistoryRoute
  MenuRoute: typeof MenuRoute
  StaffRoute: typeof StaffRouteWithChildren
  OrderIdRoute: typeof OrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/users': {
      id: '/staff/users'
      path: '/users'
      fullPath: '/staff/users'
      preLoaderRoute: typeof StaffUsersRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/panda': {
      id: '/staff/panda'
      path: '/panda'
      fullPath: '/staff/panda'
      preLoaderRoute: typeof StaffPandaRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/orders': {
      id: '/staff/orders'
      path: '/orders'
      fullPath: '/staff/orders'
      preLoaderRoute: typeof StaffOrdersRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/menu': {
      id: '/staff/menu'
      path: '/menu'
      fullPath: '/staff/menu'
      preLoaderRoute: typeof StaffMenuRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/discounts': {
      id: '/staff/discounts'
      path: '/discounts'
      fullPath: '/staff/discounts'
      preLoaderRoute: typeof StaffDiscountsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/audit': {
      id: '/staff/audit'
      path: '/audit'
      fullPath: '/staff/audit'
      preLoaderRoute: typeof StaffAuditRouteImport
      parentRoute: typeof StaffRoute
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StaffRouteChildren {
  StaffAuditRoute: typeof StaffAuditRoute
  StaffDiscountsRoute: typeof StaffDiscountsRoute
  StaffMenuRoute: typeof StaffMenuRoute
  StaffOrdersRoute: typeof StaffOrdersRoute
  StaffPandaRoute: typeof StaffPandaRoute
  StaffUsersRoute: typeof StaffUsersRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAuditRoute: StaffAuditRoute,
  StaffDiscountsRoute: StaffDiscountsRoute,
  StaffMenuRoute: StaffMenuRoute,
  StaffOrdersRoute: StaffOrdersRoute,
  StaffPandaRoute: StaffPandaRoute,
  StaffUsersRoute: StaffUsersRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  HistoryRoute: HistoryRoute,
  MenuRoute: MenuRoute,
  StaffRoute: StaffRouteWithChildren,
  OrderIdRoute: OrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
